plugins {
    id 'fabric-loom' version '1.8.11'
    id 'maven-publish'
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.11"
    mappings loom.layered {
        officialMojangMappings()
    }
    modImplementation "net.fabricmc:fabric-loader:0.18.4"
    // sem Fabric API
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}
